services:
  podsync:
    container_name: podsync
    image: ghcr.io/mxpv/podsync:latest
    restart: always
    ports:
      - 8050:8050
    volumes:
      - ${CONFIG_PATH}/podsync:/app/data/
      - ${CONFIG_PATH}/podsync/config.toml:/app/config.toml

  podconfig:
    container_name: podconfig
    image: ghcr.io/takenobou/podconfig:latest
    restart: unless-stopped
    depends_on:
      - podsync
    ports:
      - "8080:8080"
    environment:
      PODSYNC_CONFIG_PATH: "/config/config.toml"
      DOCKER_CONTAINER_NAME: "podsync"
      SERVER_PORT: "8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_PATH}/podsync/config.toml:/config/config.toml